# Generated by Django 5.2.6 on 2025-10-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_name', models.CharField(max_length=100)),
                ('coil_type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
