# Generated by Django 5.2.6 on 2025-09-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('status', models.CharField(default='Available', max_length=50)),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coils', to='getdemo.yard')),
            ],
        ),
    ]
