# Generated by Django 5.2.6 on 2025-09-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
    ]
