# Generated by Django 5.2.6 on 2025-09-26 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_id', models.CharField(max_length=50, unique=True)),
                ('material', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yard_location', models.CharField(max_length=20)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DISPATCHED', 'Dispatched'), ('SCRAP', 'Scrap')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
